terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
  required_version = ">= 0.13"
}

provider "yandex" {
  token = "${var.do_token}"
#  cloud_id  = var.cloud_id
  folder_id = "${var.do_folder_id}"
  zone      = "ru-central1-a"
}

resource "yandex_compute_instance" "manager" {
  count = 3
  name = "manager${count.index}"

  resources {
    cores  = 2
    memory = 2
    core_fraction = 20
  }

  boot_disk {
    initialize_params {
      image_id = "fd8oshj0osht8svg6rfs"
      size = 5
    }
  }

  network_interface {
    subnet_id = yandex_vpc_subnet.subnet-1.id
    nat       = true
  }
  
  metadata = {
    user-data = "${file("/home/paromov/ansible_terr_dkr/meta.txt")}"
  }

}

resource "yandex_compute_instance" "work" {
  count = 3
  name = "work${count.index}"

  resources {
    cores  = 2
    memory = 2
    core_fraction = 20
  }

  boot_disk {
    initialize_params {
      image_id = "fd8oshj0osht8svg6rfs"
      size = 5
    }
  }

  network_interface {
    subnet_id = yandex_vpc_subnet.subnet-1.id
    nat       = true
  }
  
  metadata = {
    user-data = "${file("/home/paromov/ansible_terr_dkr/meta.txt")}"
  }

}

resource "yandex_vpc_network" "network-1" {
  name = "network1"
}

resource "yandex_vpc_subnet" "subnet-1" {
  name           = "subnet1"
  zone           = "ru-central1-a"
  network_id     = yandex_vpc_network.network-1.id
  v4_cidr_blocks = ["192.168.10.0/24"]
}

resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    workers

    [managers:children]
    active
    standby

    [active]
    manager_node0=${yandex_compute_instance.manager[0].network_interface.0.nat_ip_address}

    [standby]
    manager_node1=${yandex_compute_instance.manager[1].network_interface.0.nat_ip_address}
    manager_node2=${yandex_compute_instance.manager[2].network_interface.0.nat_ip_address}

    [workers]
    worker_node0=${yandex_compute_instance.work[0].network_interface.0.nat_ip_address}
    worker_node1=${yandex_compute_instance.work[1].network_interface.0.nat_ip_address}
    worker_node2=${yandex_compute_instance.work[2].network_interface.0.nat_ip_address}
    DOC
  filename = "/home/paromov/05-virt-05-docker-swarm/inventory"

}

output "manager_name" {
  value = yandex_compute_instance.manager[*].name
}

output "work_name" {
  value = yandex_compute_instance.work[*].name
}

output "internal_ip_address_manager" {
  value = yandex_compute_instance.manager[*].network_interface.0.ip_address
}
output "external_ip_address_manager" {
  value = yandex_compute_instance.manager[*].network_interface.0.nat_ip_address
}

output "internal_ip_address_work" {
  value = yandex_compute_instance.work[*].network_interface.0.ip_address
}
output "external_ip_address_work" {
  value = yandex_compute_instance.work[*].network_interface.0.nat_ip_address
}